### ISSUE TITLE
2.35.2 is causing warnings in `choco outdated` and `roco outdated`

### ISSUE THREAD

**Issue by brian6932** [NickeManarin/ScreenToGif-Chocolatey#15]
```pwsh
❯ choco outdated
Chocolatey v0.11.3
Outdated Packages
 Output is package name | current version | available version | pinned?
screentogif.portable|2.35.2|2.35.2|false
 1 package(s) had warnings.
Warnings:
 - screentogif.portable
```

**Comment by NickeManarin** [comment]
Thanks for the feedback. I'll bump the version for the next release.
Ended up working on separating the packages and forgot to update choco.

**Comment by NickeManarin** [comment]
I would update the packages right now to v2.35.3, but there's two packages awaiting moderation (`portable` and `install`, because there were new).
