### ISSUE TITLE
ScreenToGif dependency on ffmpeg

### ISSUE THREAD

**Issue by christian-haider** [NickeManarin/ScreenToGif-Chocolatey#17]
Hi,

During installing ScreenToGif 2.38.1 I got the following msg:

`[NuGet] One or more unresolved package dependency constraints detected in the Chocolatey lib folder. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'screentogif 2.38.1 constraint: ffmpeg (>= 4.4.1 && < 6.0.0)', 'screentogif 2.38.1 constraint: screentogif.portable (>= 2.38.1)'`

Maybe you can improve this package, so that the actual version of **ffmpeg** is included (https://community.chocolatey.org/packages/ffmpeg). Right now, installing ScreenToGif, installs an OLD version of ffmpeg

thx for your work on chocolatey
Br, Christian

**Comment by brogers5** [comment]
This behavior is intentional, as ScreenToGif currently does not support FFmpeg v6.0. Consider pinning `ffmpeg` for the time being until this is implemented.

**Further reading:**
https://www.reddit.com/r/screentogif/comments/14e5mi4/ffmpeg_v6_does_not_work_with_screentogif/
PR #16

**Comment by NickeManarin** [comment]
I published v2.39 (waiting for approval), it supports v6 of FFmpeg.
