### ISSUE TITLE
Icon URL

### ISSUE THREAD

**Issue by AnthonyMastrean** [NickeManarin/ScreenToGif-Chocolatey#2]
The Icon URL (the `<iconURL />` element in the nuspec) is mostly for making your package look good on the gallery.

![image](https://cloud.githubusercontent.com/assets/217842/16163111/75948694-34a5-11e6-8176-0ee2683d6505.png)

Once you sort out the structure and naming issues in #1, you should click the file, get [the canonical URL](https://help.github.com/articles/getting-permanent-links-to-files/), and click the Raw button.

![image](https://cloud.githubusercontent.com/assets/217842/16163263/54342198-34a6-11e6-84c6-3c02ce2e5b8b.png)

Put that URL through the rawgit CDN and use the production link.

http://rawgit.com/

Use that production link in the `<iconUrl />`.

You would do this whenever you update the image.

**Comment by NickeManarin** [comment]
Done. Thanks.
