### ISSUE TITLE
Take ownership on Chocolatey.org

### ISSUE THREAD

**Issue by AnthonyMastrean** [NickeManarin/ScreenToGif-Chocolatey#4]
Fix the outstanding issues. I'll look over it one more time. When a real version update is ready to publish, I'll set you as the sole maintainer on 

https://chocolatey.org/packages/screentogif

You can publish, I'll moderate, and set your trusted package status.

:)

**Comment by AnthonyMastrean** [comment]
Do you have an account on Chocolatey?

**Comment by NickeManarin** [comment]
No, but I'm trying to create one. It looks like the website is under maintenance.

I'll try later.

**Comment by NickeManarin** [comment]
I have one under the name NickeManarin.

**Comment by AnthonyMastrean** [comment]
All done! You should be able to publish the next version. I would leave a note indicating that you're the author and ask for trusted status (in case I don't get to it personally).

**Comment by koppor** [comment]
"Package Source" still links to https://github.com/AnthonyMastrean/chocolateypackages/ instead of https://github.com/NickeManarin/ScreenToGif-Chocolatey

**Comment by NickeManarin** [comment]
I believe that the [latest package](https://chocolatey.org/packages/screentogif/2.1) is set to use [this info](https://github.com/NickeManarin/ScreenToGif-Chocolatey/blob/master/screentogif/screentogif.nuspec#L25).
