### ISSUE TITLE
New version available

### ISSUE THREAD

**Issue by nzbart** [NickeManarin/ScreenToGif-Chocolatey#8]
Thanks for providing this package!

I'm not sure if you're already aware of this or not, but there's a new version of [ScreenToGif](https://www.screentogif.com/) available. Would it be possible to update the installer to the latest version?

UPDATE: I just realised that you're also the developer of ScreenToGif, so I presume that you're already aware of the new version! I was hoping to be able to use the new feature from this issue: https://github.com/NickeManarin/ScreenToGif/issues/96.

**Comment by NickeManarin** [comment]
Oops, forgot to check this repo for a long time.
